services:
  valkey:
    image: valkey/valkey:alpine-latest
    container_name: valkey
    ports:
      - "6379:6379"
      - "8080:8080"
    volumes:
      - valkey-data:/data
      - ./valkey-config:/etc/valkey
    environment:
      - VALKEY_LOG_LEVEL=info
      - VALKEY_DATA_DIR=/data
    restart: unless-stopped

  dnsblrsd:
    build: .
    container_name: dnsblrsd
    ports:
      # make sure the ports here expose the ports defined in the services of dnslbrsd.conf
      #- "53:53/udp"
      #- "53:53/tcp"
    cap_add:
      - NET_BIND_SERVICE
    volumes:
      - ./dnsblrsd.conf:/etc/dnsblrsd/dnsblrsd.conf:ro
    restart: unless-stopped
    depends_on:
      - valkey

volumes:
  valkey-data:
