name: Rust cargo build & test

on:
  push:
    branches:
      - main
      - dev
    paths-ignore: "**.md"

  pull_request:
    branches:
      - main
      - dev
    paths-ignore: "**.md"

env:
  CARGO_TERM_COLOR: always

jobs:
  dnsblrsd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build dnsblrsd
        run: cargo build -p dnsblrsd --verbose
      - name: Test dnsblrsd
        run: cargo test -p dnsblrsd --verbose

  redis-ctl:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build redis-ctl
        run: cargo build -p redis-ctl --verbose
